/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    properties: Property;
    bookings: Booking;
    reviews: Review;
    payouts: Payout;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    properties: PropertiesSelect<false> | PropertiesSelect<true>;
    bookings: BookingsSelect<false> | BookingsSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    payouts: PayoutsSelect<false> | PayoutsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'user' | 'provider' | 'admin';
  firstName: string;
  lastName: string;
  phone?: string | null;
  bio?: string | null;
  avatar?: (number | null) | Media;
  favorites?: (number | Property)[] | null;
  providerInfo?: {
    businessName?: string | null;
    businessType?: ('individual' | 'llc' | 'corporation') | null;
    stripeAccountId?: string | null;
    stripeOnboarded?: boolean | null;
    verified?: boolean | null;
  };
  notifications?: {
    emailBookings?: boolean | null;
    emailMarketing?: boolean | null;
    smsBookings?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties".
 */
export interface Property {
  id: number;
  name: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  owner: number | User;
  status: 'pending' | 'active' | 'inactive' | 'suspended';
  type: 'residential' | 'commercial' | 'restaurant' | 'hotel';
  location: {
    address: string;
    city: string;
    state: string;
    zipCode: string;
    country?: string | null;
    /**
     * @minItems 2
     * @maxItems 2
     */
    coordinates: [number, number];
  };
  /**
   * Price in cents per minute
   */
  pricePerMinute: number;
  /**
   * Minimum booking duration in minutes
   */
  minimumDuration: number;
  /**
   * Maximum booking duration in minutes
   */
  maximumDuration: number;
  amenities?:
    | (
        | 'wheelchair'
        | 'baby_changing'
        | 'shower'
        | 'bidet'
        | 'air_freshener'
        | 'hand_dryer'
        | 'paper_towels'
        | 'feminine'
        | 'mirror'
        | 'climate'
        | 'private'
        | 'gender_neutral'
      )[]
    | null;
  photos?:
    | {
        image: number | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  availability?: {
    instantBooking?: boolean | null;
    /**
     * Minutes of advance notice required
     */
    advanceNotice?: number | null;
    /**
     * Buffer time between bookings in minutes
     */
    bufferTime?: number | null;
    schedule?:
      | {
          day: 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
          enabled?: boolean | null;
          startTime: string;
          endTime: string;
          id?: string | null;
        }[]
      | null;
  };
  stats?: {
    totalBookings?: number | null;
    totalEarnings?: number | null;
    averageRating?: number | null;
    reviewCount?: number | null;
  };
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings".
 */
export interface Booking {
  id: number;
  user?: (number | null) | User;
  property: number | Property;
  startTime: string;
  endTime: string;
  /**
   * Duration in minutes
   */
  duration?: number | null;
  status: 'pending' | 'confirmed' | 'in_progress' | 'completed' | 'cancelled' | 'refunded' | 'no_show';
  /**
   * Total amount in cents
   */
  totalAmount?: number | null;
  /**
   * Platform fee in cents
   */
  platformFee?: number | null;
  /**
   * Provider payout in cents
   */
  providerPayout?: number | null;
  stripePaymentIntentId?: string | null;
  accessCode?: string | null;
  accessInstructions?: string | null;
  cancellation?: {
    cancelledAt?: string | null;
    cancelledBy?: (number | null) | User;
    reason?: string | null;
    refundAmount?: number | null;
  };
  /**
   * Automatically set when user submits a review
   */
  hasBeenReviewed?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  booking: number | Booking;
  property: number | Property;
  user: number | User;
  rating: number;
  cleanliness?: number | null;
  accuracy?: number | null;
  communication?: number | null;
  comment: string;
  response?: {
    comment?: string | null;
    respondedAt?: string | null;
  };
  /**
   * Flag inappropriate reviews
   */
  reported?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts".
 */
export interface Payout {
  id: number;
  provider: number | User;
  /**
   * Amount in cents
   */
  amount: number;
  status: 'pending' | 'processing' | 'completed' | 'failed';
  stripeTransferId?: string | null;
  /**
   * Bookings included in this payout
   */
  bookings?: (number | Booking)[] | null;
  periodStart: string;
  periodEnd: string;
  processedAt?: string | null;
  failureReason?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'properties';
        value: number | Property;
      } | null)
    | ({
        relationTo: 'bookings';
        value: number | Booking;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'payouts';
        value: number | Payout;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  firstName?: T;
  lastName?: T;
  phone?: T;
  bio?: T;
  avatar?: T;
  favorites?: T;
  providerInfo?:
    | T
    | {
        businessName?: T;
        businessType?: T;
        stripeAccountId?: T;
        stripeOnboarded?: T;
        verified?: T;
      };
  notifications?:
    | T
    | {
        emailBookings?: T;
        emailMarketing?: T;
        smsBookings?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "properties_select".
 */
export interface PropertiesSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  owner?: T;
  status?: T;
  type?: T;
  location?:
    | T
    | {
        address?: T;
        city?: T;
        state?: T;
        zipCode?: T;
        country?: T;
        coordinates?: T;
      };
  pricePerMinute?: T;
  minimumDuration?: T;
  maximumDuration?: T;
  amenities?: T;
  photos?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  availability?:
    | T
    | {
        instantBooking?: T;
        advanceNotice?: T;
        bufferTime?: T;
        schedule?:
          | T
          | {
              day?: T;
              enabled?: T;
              startTime?: T;
              endTime?: T;
              id?: T;
            };
      };
  stats?:
    | T
    | {
        totalBookings?: T;
        totalEarnings?: T;
        averageRating?: T;
        reviewCount?: T;
      };
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bookings_select".
 */
export interface BookingsSelect<T extends boolean = true> {
  user?: T;
  property?: T;
  startTime?: T;
  endTime?: T;
  duration?: T;
  status?: T;
  totalAmount?: T;
  platformFee?: T;
  providerPayout?: T;
  stripePaymentIntentId?: T;
  accessCode?: T;
  accessInstructions?: T;
  cancellation?:
    | T
    | {
        cancelledAt?: T;
        cancelledBy?: T;
        reason?: T;
        refundAmount?: T;
      };
  hasBeenReviewed?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  booking?: T;
  property?: T;
  user?: T;
  rating?: T;
  cleanliness?: T;
  accuracy?: T;
  communication?: T;
  comment?: T;
  response?:
    | T
    | {
        comment?: T;
        respondedAt?: T;
      };
  reported?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payouts_select".
 */
export interface PayoutsSelect<T extends boolean = true> {
  provider?: T;
  amount?: T;
  status?: T;
  stripeTransferId?: T;
  bookings?: T;
  periodStart?: T;
  periodEnd?: T;
  processedAt?: T;
  failureReason?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}